.TH "GIT-PW SERIES SHOW" "1" "2023-05-08" "2.4.1" "git-pw series show Manual"
.SH NAME
git-pw\-series\-show \- Show information about series.
.SH SYNOPSIS
.B git-pw series show
[OPTIONS] SERIES_ID
.SH DESCRIPTION
Show information about series.
.PP
    Retrieve Patchwork metadata for a series.

.SH OPTIONS
.TP
\fB\-f,\fP \-\-format [simple|table|csv|yaml]
Output format. Defaults to the value of 'git config pw.format' else 'table'.
