.TH "GIT-PW SERIES APPLY" "1" "2023-05-08" "2.4.1" "git-pw series apply Manual"
.SH NAME
git-pw\-series\-apply \- Apply series.
.SH SYNOPSIS
.B git-pw series apply
[OPTIONS] SERIES_ID [ARGS]...
.SH DESCRIPTION
Apply series.
.PP
    Apply a series locally using the 'git-am' command. Any additional ARGS
    provided will be passed to the 'git-am' command.
