.TH "GIT-PW BUNDLE DELETE" "1" "2023-05-08" "2.4.1" "git-pw bundle delete Manual"
.SH NAME
git-pw\-bundle\-delete \- Delete a bundle.
.SH SYNOPSIS
.B git-pw bundle delete
[OPTIONS] BUNDLE_ID
.SH DESCRIPTION
Delete a bundle.
.PP
    Delete bundle BUNDLE_ID.
.PP
    Requires API version 1.2 or greater.

.SH OPTIONS
.TP
\fB\-f,\fP \-\-format [simple|table|csv|yaml]
Output format. Defaults to the value of 'git config pw.format' else 'table'.
