.TH "GIT-PW BUNDLE DOWNLOAD" "1" "2023-05-08" "2.4.1" "git-pw bundle download Manual"
.SH NAME
git-pw\-bundle\-download \- Download bundle in mbox format.
.SH SYNOPSIS
.B git-pw bundle download
[OPTIONS] BUNDLE_ID [OUTPUT]
.SH DESCRIPTION
Download bundle in mbox format.
.PP
    Download a bundle but do not apply it. ``OUTPUT`` is optional and can be an
    output full file path or a directory or ``-`` to output to ``stdout``. If
    ``OUTPUT`` is not provided, the output path will be automatically chosen.
