.TH "GIT-PW PATCH DOWNLOAD" "1" "2023-05-08" "2.4.1" "git-pw patch download Manual"
.SH NAME
git-pw\-patch\-download \- Download patch in diff or mbox format.
.SH SYNOPSIS
.B git-pw patch download
[OPTIONS] PATCH_ID [OUTPUT]
.SH DESCRIPTION
Download patch in diff or mbox format.
.PP
    Download a patch but do not apply it. ``OUTPUT`` is optional and can be an
    output file path or a directory or ``-`` to output to ``stdout``. If
    ``OUTPUT`` is not provided, the output path will be automatically chosen.

.SH OPTIONS
.TP
\fB\-\-diff\fP
Show patch in diff format.
.TP
\fB\-\-mbox\fP
Show patch in mbox format.
