.TH "GIT-PW PATCH LIST" "1" "2023-05-08" "2.4.1" "git-pw patch list Manual"
.SH NAME
git-pw\-patch\-list \- List patches.
.SH SYNOPSIS
.B git-pw patch list
[OPTIONS] [NAME]
.SH DESCRIPTION
List patches.
.PP
    List patches on the Patchwork instance.

.SH OPTIONS
.TP
\fB\-\-state\fP STATE
Show only patches matching these states. Should be slugified representations of states. The available states are instance dependant.
.TP
\fB\-\-submitter\fP SUBMITTER
Show only patches by these submitters. Should be an email, name or ID.
.TP
\fB\-\-delegate\fP DELEGATE
Show only patches with these delegates. Should be an email or username.
.TP
\fB\-\-hash\fP HASH
Show only patches with these hashes.
.TP
\fB\-\-archived\fP
Include patches that are archived.
.TP
\fB\-\-sort\fP FIELD
Sort output on given field.
.TP
\fB\-\-page\fP PAGE
Page to retrieve items from. This is influenced by the size of LIMIT.
.TP
\fB\-\-limit\fP LIMIT
Maximum number of items to show.
.TP
\fB\-c,\fP \-\-column COLUMN
Columns to be included in output.
.TP
\fB\-f,\fP \-\-format [simple|table|csv|yaml]
Output format. Defaults to the value of 'git config pw.format' else 'table'.
