.TH "GIT-PW BUNDLE UPDATE" "1" "2023-05-08" "2.4.1" "git-pw bundle update Manual"
.SH NAME
git-pw\-bundle\-update \- Update a bundle.
.SH SYNOPSIS
.B git-pw bundle update
[OPTIONS] BUNDLE_ID
.SH DESCRIPTION
Update a bundle.
.PP
    Update bundle BUNDLE_ID. If PATCH_IDs are specified, this will overwrite
    all patches in the bundle. Use 'bundle add' and 'bundle remove' to add or
    remove patches.
.PP
    Requires API version 1.2 or greater.

.SH OPTIONS
.TP
\fB\-\-name\fP TEXT
.PP
.TP
\fB\-\-patch\fP INTEGER
Add the specified patch(es) to the bundle.
.TP
\fB\-\-public\fP / \-\-private
Allow other users to view this bundle. If private, only you will be able to see this bundle.
.TP
\fB\-f,\fP \-\-format [simple|table|csv|yaml]
Output format. Defaults to the value of 'git config pw.format' else 'table'.
