.TH "GIT-PW BUNDLE APPLY" "1" "21-Sep-2019" "1.7.0" "git-pw bundle apply Manual"
.SH NAME
git-pw\-bundle\-apply \- Apply bundle.
.SH SYNOPSIS
.B git-pw bundle apply
[OPTIONS] BUNDLE_ID [ARGS]...
.SH DESCRIPTION
Apply bundle.
.PP
Apply a bundle locally using the 'git-am' command. Any additional ARGS
provided will be passed to the 'git-am' command.
