.TH "GIT-PW SERIES DOWNLOAD" "1" "2023-05-08" "2.4.1" "git-pw series download Manual"
.SH NAME
git-pw\-series\-download \- Download series in mbox format.
.SH SYNOPSIS
.B git-pw series download
[OPTIONS] SERIES_ID [OUTPUT]
.SH DESCRIPTION
Download series in mbox format.
.PP
    Download a series but do not apply it. ``OUTPUT`` is optional and can be an
    output path or ``-`` to output to ``stdout``. If ``OUTPUT`` is not
    provided, the output path will be automatically chosen.

.SH OPTIONS
.TP
\fB\-\-separate\fP
Download each series patch to a separate file
.TP
\fB\-\-combined\fP
Download all series patches to one file
