.TH "GIT-PW BUNDLE SHOW" "1" "2023-05-08" "2.4.1" "git-pw bundle show Manual"
.SH NAME
git-pw\-bundle\-show \- Show information about bundle.
.SH SYNOPSIS
.B git-pw bundle show
[OPTIONS] BUNDLE_ID
.SH DESCRIPTION
Show information about bundle.
.PP
    Retrieve Patchwork metadata for a bundle.

.SH OPTIONS
.TP
\fB\-f,\fP \-\-format [simple|table|csv|yaml]
Output format. Defaults to the value of 'git config pw.format' else 'table'.
