---
version: 2
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"
  jobs:
    post_checkout:
      - git fetch --unshallow
