[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "git-pw"
dynamic = ["version"]
description = "Git-Patchwork integration tool"
readme = "README.rst"
license = "MIT"
authors = [
    { name = "Stephen Finucane", email = "stephen@that.guru" },
]
keywords = [
    "git",
    "patchwork",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
]

dependencies = [
    "click>=6.0,",
    "requests>=2.0",
    "tabulate>=0.8",
    "arrow>=0.10",
    "PyYAML>=5.1",
]

[project.urls]
"Bug Tracker" = "https://github.com/getpatchwork/git-pw/issues"
Documentation = "https://git-pw.readthedocs.io"
Homepage = "https://github.com/getpatchwork/git-pw"
"Source Code" = "https://github.com/getpatchwork/git-pw"

[project.scripts]
git-pw = "git_pw.shell:cli"

[tool.hatch.version]
path = "git_pw/__init__.py"

[tool.hatch.build.targets.sdist]
include = [
    "/git_pw",
]

[tool.black]
line-length = 79
skip-string-normalization = true
