[tox]
minversion = 4.6
envlist = pep8,mypy,clean,py{39,310,311,312,313},report

[testenv]
deps =
  -r{toxinidir}/test-requirements.txt
commands =
  pytest -Wall --cov=git_pw --cov-report term-missing {posargs}

[testenv:pep8]
skip_install = true
deps =
  pre-commit
commands =
  pre-commit run --all-files --show-diff-on-failure

[testenv:mypy]
deps=
  mypy
  types-PyYAML
  types-requests
  types-setuptools
  types-tabulate
commands=
  mypy --cache-dir="{envdir}/mypy_cache" {posargs:git_pw}

[testenv:report]
skip_install = true
deps =
  coverage
commands =
  coverage report
  coverage html

[testenv:clean]
envdir = {toxworkdir}/report
skip_install = true
deps =
  {[testenv:report]deps}
commands =
  coverage erase

[testenv:docs]
deps =
  -r{toxinidir}/docs/requirements.txt
commands =
  sphinx-build {posargs:-E -W} docs docs/_build/html

[testenv:man]
deps =
  click-man~=0.5.1
commands =
  click-man git-pw
